layout_spectrum: 0.1000257
typography_spectrum: 0.6308056
color:
  saturation: 0.5941184
  lightness: 0.5571866
  brandStrength: 0.06014596
  rhythmicContrast: 0.3364713
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Patches
